### ISSUE TITLE
Code review 19/04

### ISSUE THREAD

**Issue by KaanKalmi** [J3SS3HVA/user-experience-enhanced-website#3]
### EJS, Server.js, JS
Alles dat me opviel is al genoemd door Samara en Yu Jing 😭 

### CSS
```css
div,
img,
article {
  border-radius: 6px;
}
```
je kan zulke dingen beter op de volgende manier schrijven:
```css
div, img, article {
  border-radius: 6px;
}
```
Dit heeft te maken met performance, hoe kleiner je CSS bestand hoe sneller het inlaad, dus als je meerdere elementen selecteert, doe ze lekker op 1 lijn!

Kijk ook eens ff naar CSS Nesting, ik zie dat je 
```css
.family article img {
  width: 100px;
  height: 100px;
  object-fit: cover;
  border-radius: 50%;
}

.family article div {
  margin-left: 2em; 
}


.family article div h2{
  color: var(--primary-color);
}

.family article div p{
  font-size: 0.5em;
}
```
Hebt gedaan, wat ik kan begrijpen maar kijk of je het met nesting misschien kan verkorten/verduidelijken (bron: [CSS Nesting](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting)
